apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "successful-ssh-connections"
spec:
  kprobes:
  - call: "tcp_sendmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
    - index: 2
      type: int
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/sbin/sshd"
#    - matchArgs: # tried this with altered CRDs
#      - index: 0
#        operator: "Priority"
#        values:
#        - "6"
  - call: "inet_csk_accept"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/sbin/sshd"
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/sbin/sshd"