apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-scp-usage"
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
 #   - matchBinaries:
 #     - operator: "In"
 #       values:
 #       - "/usr/bin/sftp"
 #       - "/usr/lib/openssh/sftp-server"
 #       - "/usr/bin/scp"
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/usr/lib/openssh/sftp-server"
