# https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-21626
# This was given to me from djalal 
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "leaky-vessel"
  annotations:
    url: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-21626
    description: "Prevents exploitation of runc CVE-2024-21626"
    author: "Tetragon.io Team/ modified by entlein"
spec:
  kprobes:
  - call: "sys_chdir"
    syscall: true
    args:
      - index: 0
        type: "string"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        # Add your runc paths here
        - "/usr/bin/runc"
        - "/usr/sbin/runc"
        - "/usr/local/sbin/runc"
        - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/containerd-shim-runc-v2"
        - "/var/lib/rancher/rke2/data/v1.27.9-rke2r1-bfe115e44df3/bin/containerd-shim-runc-v2"
        - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/runc"
        - "/var/lib/rancher/rke2/bin/runc"
        - "/var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd-shim-runc-v2"
        - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/runc"
        - "/var/lib/rancher/rke2/data/v1.27.9-rke2r1-bfe115e44df3/bin/runc"
      matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/proc/self/fd/"
  # - call: "sys_execve"
  #   syscall: true
  #   args:
  #   - index: 0
  #     type: "string"
  #   selectors:
    #- matchBinaries:
    #  - operator: "In"
    #    values:
    #    - "/var/lib/rancher/rke2/bin/runc"
    #    - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/containerd-shim-runc-v2"
      #   - "/usr/bin/runc"
      #   - "/usr/sbin/runc"
      #   - "/usr/local/sbin/runc"
      #   - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/containerd-shim-runc-v2"
      #   - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/runc"
      #   - "/var/lib/rancher/rke2/bin/runc"
    # - matchArgs:
    #   - index: 0
    #     operator: "Equal"
    #     values:
    #     - "/usr/bin/runc"
    #     - "/usr/sbin/runc"
    #     - "/usr/local/sbin/runc"
    #     - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/containerd-shim-runc-v2"
    #     - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/runc"
    #     - "/var/lib/rancher/rke2/bin/runc"
  # - call: "set_fs_pwd"
  #   syscall: false
  #   args:
  #     - index: 1
  #       type: "path"
  #   selectors:
  #   - matchBinaries:
  #     - operator: "In"
  #       values:
  #       # Add your runc paths here
  #       - "/usr/bin/runc"
  #       - "/usr/sbin/runc"
  #       - "/usr/local/sbin/runc"
  #       - "/var/lib/rancher/rke2/data/v1.27.10-rc2-rke2r1-2009b566493e/bin/containerd-shim-runc-v2"
  #       - "/var/lib/rancher/rke2/bin/runc"
  #     matchArgs:
  #     - index: 1
  #       operator: "Prefix"
  #       values:
  #       - "/sys/fs/cgroup"
  # - call: "chdir"
  #   syscall: true
  #   args:
  #   - index: 0
  #     type: "string"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "/proc/self/fd/9"
  #       - "/proc/self/fd/8"
  # - call: "sys_openat"
  #   return: true
  #   syscall: true
  #   args:
  #   - index: 0
  #     type: int
  #   - index: 1
  #     type: "string"
  #   - index: 2
  #     type: "int"
  #   returnArg:
  #     index: 0
  #     type: int
  #   selectors:
  #   - matchArgs:
  #     - index: 1
  #       operator: "Equal"
  #       values:
  #       - "/proc/self/fd/9"
  #       - "/proc/self/fd/8"
  #     - index: 2
  #       operator: "Mask"
  #       values:
  #       - "64" # CREATE (0x40)
  #       - "1"  # WRONLY (0x01)
  #       - "2"  # RDWR (0x02)
  #     matchReturnArgs:
  #     - index: 0
  #       operator: "GT"
  #       values:
  #       - "0"
  # - call: "dup2"
  #   syscall: true
  #   args:
  #   - index: 0
  #     type: "int"
  #   - index: 1
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "9"
  #       - "8"
  # - call: "fcntl"
  #   syscall: true
  #   args:
  #   - index: 0
  #     type: "int"
  #   - index: 1
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "9"
  #       - "8"