---
apiVersion: v1
kind: Pod
metadata:
  name: ssh-proxy
  labels:
    app.kubernetes.io/name: ssh-proxy
spec:
  containers:
    - name: ssh-proxy
      image: jamescallaghan1987/insecure_ssh:latest
      imagePullPolicy: Always
      ports:
        - name: ssh-port
          containerPort: 22

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-proxy
  labels:
    app.kubernetes.io/name: ssh-proxy
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    app.kubernetes.io/name: ssh-proxy

