---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-proxy
  labels:
    app: ssh-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-proxy
  template:
    metadata:
      labels:
        app: ssh-proxy
    spec:
      containers:
      - name: ssh-proxy
        image: entlein/ssh-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-proxy
  labels:
    app: ssh-proxy
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    app: ssh-proxy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssh-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "SSH"
spec:
  ingressClassName: nginx
  rules:
  - host: ssh.caas-0009.dev.austrianopencloudcommunity.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ssh-proxy
            port:
              number: 22


