---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-proxy
  labels:
    app: ssh-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-proxy
  template:
    metadata:
      labels:
        app: ssh-proxy
    spec:
      containers:
      - name: ssh-proxy
        image: entlein/ssh-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-proxy
  labels:
    app: ssh-proxy
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    app: ssh-proxy

